name: Setup Node and PNPM
description: Set up Node.js and PNPM

inputs:
  node-version:
    description: The version of Node.js to install
    required: false

  pnpm-version:
    description: The version of PNPM to install
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Set NODE_VERSION from package.json
      run: pnpm --filter=repo-actions actions:set-node-env
      shell: bash
