# Note: https://github.com/JS-DevTools/npm-publish

name: Publish
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  push:
    branches:
      - main
# Ensure that two published workflows don't happen at the same time
concurrency: ${{ github.workflow }}-${{ github.ref }}



jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node-env

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
